/** Common HTTP status codes (RFC 9110 / registry). */
export const HTTP_STATUS_CODES: { code: number; phrase: string; description: string }[] = [
  { code: 100, phrase: "Continue", description: "Request received; client may continue." },
  { code: 101, phrase: "Switching Protocols", description: "Server agrees to protocol switch." },
  { code: 102, phrase: "Processing", description: "Request is being processed (WebDAV)." },
  { code: 103, phrase: "Early Hints", description: "Hints while preparing a final response." },
  { code: 200, phrase: "OK", description: "Request succeeded." },
  { code: 201, phrase: "Created", description: "Resource created." },
  { code: 202, phrase: "Accepted", description: "Accepted for processing (async)." },
  { code: 204, phrase: "No Content", description: "Success with no body." },
  { code: 206, phrase: "Partial Content", description: "Range request fulfilled." },
  { code: 301, phrase: "Moved Permanently", description: "URI permanently moved." },
  { code: 302, phrase: "Found", description: "Temporary redirect (often POST→GET)." },
  { code: 303, phrase: "See Other", description: "GET the URI in Location." },
  { code: 304, phrase: "Not Modified", description: "Cached version still valid." },
  { code: 307, phrase: "Temporary Redirect", description: "Same method to new URI." },
  { code: 308, phrase: "Permanent Redirect", description: "Permanent; method preserved." },
  { code: 400, phrase: "Bad Request", description: "Malformed syntax." },
  { code: 401, phrase: "Unauthorized", description: "Authentication required." },
  { code: 403, phrase: "Forbidden", description: "Authenticated but not allowed." },
  { code: 404, phrase: "Not Found", description: "Resource does not exist." },
  { code: 405, phrase: "Method Not Allowed", description: "HTTP method not supported." },
  { code: 409, phrase: "Conflict", description: "State conflict with request." },
  { code: 410, phrase: "Gone", description: "Resource permanently removed." },
  { code: 413, phrase: "Payload Too Large", description: "Request body too large." },
  { code: 415, phrase: "Unsupported Media Type", description: "Format not supported." },
  { code: 422, phrase: "Unprocessable Entity", description: "Semantic errors in body." },
  { code: 429, phrase: "Too Many Requests", description: "Rate limited." },
  { code: 500, phrase: "Internal Server Error", description: "Unexpected server error." },
  { code: 501, phrase: "Not Implemented", description: "Server does not support capability." },
  { code: 502, phrase: "Bad Gateway", description: "Invalid response from upstream." },
  { code: 503, phrase: "Service Unavailable", description: "Temporarily overloaded or down." },
  { code: 504, phrase: "Gateway Timeout", description: "Upstream timed out." }
];
